# docker-compose.yml
version: "3"
services:
  darkdot-substrate:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: d4rk/dark-node:latest
    container_name: dark-node
    network_mode: "host"
    restart: on-failure
    volumes:
      - chain_data:/data
    command: ./dark-node --dev

volumes:
  chain_data:
    driver: local
